apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techops-manager-app
  namespace: argocd # This is where ArgoCD itself is installed
spec:
  project: techops-manager
  source:
    repoURL: https://github.com/avisubir350/techops-config.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: techops # All resources will be sent here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # IMPORTANT: Tells Argo to create 'weather' if it doesn't exist
